/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_yuangudashen_testcpp_testmakeso1_NativeUtils.h"
/* Header for class com_yuangudashen_testcpp_testmakeso1_NativeUtils */

/*
 * Class:     com_yuangudashen_testcpp_testmakeso1_NativeUtils
 * Method:    testAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL
Java_com_yuangudashen_testcpp_testmakeso1_NativeUtils_testAdd
  (JNIEnv *env, jclass obj, jint a, jint b){
    return a + b;}

