/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yuangudashen_testcpp_testmakeso1_NativeUtils */

#ifndef _Included_com_yuangudashen_testcpp_testmakeso1_NativeUtils
#define _Included_com_yuangudashen_testcpp_testmakeso1_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yuangudashen_testcpp_testmakeso1_NativeUtils
 * Method:    testAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL
Java_com_yuangudashen_testcpp_testmakeso1_NativeUtils_testAdd
  (JNIEnv *env, jclass obj, jint a, jint b);

#ifdef __cplusplus
}
#endif
#endif
